config/routes.rb
Together::Application.routes.draw do
  resources :events do
    resources :attendees, except: [:show]
  end

  root :to => 'welcome#index'

end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
  validates :name, presence: true 
  belongs_to :event
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 3 }
  has_many :attendees
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale
  def set_locale
    if params[:locale] && I18n.available_locales.include?( params[:locale].to_sym )
      session[:locale] = params[:locale]
    end
    I18n.locale = session[:locale] || I18n.default_locale
  end 



end

app/controllers/attendees_controller.rb
class AttendeesController < ApplicationController
  before_action :set_event
  before_action :set_attendee, only:[:edit, :update]
  def index
    @attendees = @event.attendees
  end

  def new
    @attendee = Attendee.new
  end

  def create
    if @event.attendees.create(attendee_params)
      redirect_to :action => "index"
    else
      render action: 'new'
    end
  end

  def edit
  end

  def update
    if @attendee.update(attendee_params)
      redirect_to :action => "index"
    else
      render action 'edit'
    end
  end

  def destroy
    @event.attendees.destroy(params[:id])
    redirect_to :action => "index" 
  end

  private
  def set_event
    @event = Event.find(params[:event_id])
  end

  def set_attendee
    @attendee = @event.attendees.find(params[:id])
  end

  def attendee_params
    params.require(:attendee).permit(:name, :email, :phone, :comment)
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.all
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_at)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendees_helper.rb
module AttendeesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/attendees/_form.html.erb
<%= simple_form_for ([@event, @attendee]) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :phone %>
    <%= f.input :comment %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
    <%= link_to t(".Back"), event_attendees_path(@event), :class => "btn"%>
  </div>
<% end %>

app/views/attendees/edit.html.erb
<h1>Editing attendee</h1>
<%= render 'form' %>

app/views/attendees/index.html.erb
<h1><%= t(".Attendees list") %></h1>
<table class="table">
  <thead>
    <tr>
      <th><%= Attendee.human_attribute_name(:name)%></th>
      <th><%= Attendee.human_attribute_name(:email)%></th>
      <th><%= Attendee.human_attribute_name(:phone)%></th>
      <th><%= Attendee.human_attribute_name(:comment)%></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attendees.each do |attendee| %>
      <tr>
        <td> <%= attendee.name %> </td>
        <td> <%= attendee.email %> </td>
        <td> <%= attendee.phone %> </td>
        <td> <%= attendee.comment %> </td>
        <td>
          <div class="btn-group">
            <%= link_to t(".Edit"), edit_event_attendee_path(@event,attendee), :class => "btn"%>
            <%= link_to t(".Destroy"), event_attendee_path(@event,attendee), method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t(".Attend"), new_event_attendee_path(@event), :class => "btn" %>
<%= link_to t(".Back"), event_path(@event), :class => "btn"%>

app/views/attendees/new.html.erb
<h1><%= t(".New attendee") %></h1>
<%= render 'form' %>

app/views/events/_form.html.erb
<%= simple_form_for(@event) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :start_at %>
  </div>

  <div class="form-actions">
    <%= f.button :submit , :class =>"btn btn-primary"%>
    <%= link_to t(".Back"), events_path, :class => "btn" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1><%= t(".Editing event") %></h1>
<%= render 'form' %>

app/views/events/index.html.erb
<h1><%= t(".title") %></h1>

<table class="table">
  <thead>
    <tr>
      <th> <%= Event.human_attribute_name(:name) %> </th>
      <th> <%= Event.human_attribute_name(:description)%> </th>
      <th> <%= Event.human_attribute_name(:start_at) %></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td><%= event.start_at %></td>
        <td>
          <div class="btn-group">
            <%= link_to t(".Attend"), new_event_attendee_path(event), :class => "btn" %>
            <%= link_to t(".Show"), event, :class => "btn"%>
            <%= link_to t('.Edit'), edit_event_path(event), :class =>"btn" %>
            <%= link_to t('.Destroy'), event, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"btn" %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.New Event'), new_event_path, :class => "btn btn-primary" %>

app/views/events/new.html.erb
<h1><%= t(".New event") %></h1>

<%= render 'form' %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>
<div class="hero-unit">
  <p>
  <strong><%= t(".Name") %></strong>
  <%= @event.name %>
  </p>

  <p>
  <strong><%= t(".Description") %></strong>
  <%= @event.description %>
  </p>

  <p>
  <strong><%= t(".Start at")%></strong>
  <%= @event.start_at %>
  </p>
  <%= link_to t(".Attendees list"), event_attendees_path(@event), :class =>"btn"%>
  <div class="btn-group">
    <%= link_to t(".Edit"), edit_event_path(@event), :class => "btn" %>
    <%= link_to t(".Back"), events_path, :class => "btn" %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Together</title>
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div class="container">
      <div class="content">

        <div class="wrapper">
          <div class="proper-content">
            <div class="row">
              <div class="span9 offset1">
                <%= yield %>
              </div>
            </div>
          </div>
        </div>
        <div class="footer-wrapper">
          <footer>
          <%= link_to "中⽂文版",
            :controller => controller.controller_name,
            :action => controller.action_name,
            :locale => "zh-TW" %> | 
            <%= link_to "English",
            :controller => controller.controller_name,
            :action => controller.action_name,
            :locale => "en" %>
            </footer>
          </div>
        </body>
      </html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>
<h1><%= link_to t("home"), root_path %></h1>